### ISSUE TITLE
QueueMessageChannel setting timeout overwrites SQS Delivery Delay setting

### ISSUE THREAD

**Issue by demboos** [spring-cloud/spring-cloud-aws#141]
QueueMessageChannel implementation of sendInternal(Message<?> message, long timeout) uses the timeout parameter to specify the withDelaySeconds (delivery delay of message). This overwrites the default setting of the SQS queue. The problem is that
1)  QueueMessageChannel does this always (so the SQS queue setting is never respected)
2) The default value of the timeout parameter of sendInternal is -1, see AbstractMessageChannel.send(Message<?> message)

As a result, there is no way to specify the delivery delay, because the queue setting is overwritten, and there is no way to use the send(Message<?> message, long timeout) method of AbstractMessageChannel, as the QueueMessagingTemplate does not expose it.

**Comment by alainsahli** [comment]
Hi @demboos,

I changed the way the delay is set on a `SendMessageRequest` (a86650a). Now if no delay is defined it is not set on the request object.

To specify a delay on a message, a header must be set `SqsMessageHeaders.SQS_DELAY_HEADER` with the desired value (c689346).

These changes were done on the 1.2.x branch as it contains breaking changes (AmazonSQSAsync is now used instead of AmazonSQS).
