### ISSUE TITLE
SimpleMessageListenerContainerFactory doesn't expose queueStopTimeout property from the SimpleMessageListenerContainer

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-aws#158]
See https://github.com/spring-projects/spring-integration-aws/issues/36 for more information.

Revise if any other properties have been omitted as well.

**Comment by alainsahli** [comment]
Hi @artembilan,

I added the property `queueStopTimeout` as XML attribute (1ad2e600450d8d6c5a7efd579c5e05ff5cb127cc) and on the container factory (6d73d9eff168d7937b77f3862442223003a6b2fb).

**Comment by artembilan** [comment]
Excellent , @alainsahli !
Thank you very much.

Although we to rules do not modify XSD for point releases, because it would be some overhead to have `-1.1.1.xsd`, too :smile: 

Nevertheless I see that you even don't `-1.1.xsd` :wink: 
In Spring Integration we decided even don't keep previous xsd version in the current major/minor versions.
In other words I'd just rename that `-1.0.xsd` to `-1.1.xsd`.
But eh... it would be better do not expose more attributes into XSD in point releases. That confuses end-users a bit.

**Comment by alainsahli** [comment]
Hi @artembilan,

I reverted all changes regarding this property (e29a7c94e538b9510240028505cd195954ddcc39 and 0664261225643d11822572633a680d02166e2929). Even on the SimpleMessageListenerContainerFactory because I didn't want to introduce potential compile errors when downgrading the versions along the 1.1.x branch.

I pushed everything on a new branch `1.2.x`.
