### ISSUE TITLE
AWS Redirects are not honored when using the S3Resource

### ISSUE THREAD

**Issue by mminella** [spring-cloud/spring-cloud-aws#192]
When AWS returns a redirect when querying a S3 bucket via the S3Resource, we are not honoring it.  Unfortunately, it seems that AWS does not return the new URL as a header to follow anyways, however it does seem to be returning an XML document that has the URL in it.  It would be helpful if there was some way to honor that redirect since most other S3 clients seem to handle it transparently.

This issue can be illustrated by using this project against an S3 bucket with a redirect: https://github.com/mminella/S3JDBC.

**Comment by gregturn** [comment]
@mminella I opened #96 a long time ago, but the project leads won't bite.

**Comment by aemruli** [comment]
@mminella sorry for the late reply. As @gregturn pointed out there is already a PR available long time ago. While I think that the PR works fine I did not merge it in the past because with the proxy we are constantly changing the endpoint URL to follow the redirects. 
With the introduction of immutable clients in the AWS SDK this will not work. I think in the time-being you can move on if you are on the 1.2.x (master) branch. We will change the proxy implementation to use multiple (e.g. one client per region) and do the redirects without changing the endpoint url. 

I will leave the ticket open until the redirects are properly implemented.

**Comment by aemruli** [comment]
fixed with b6db51bb1087d4a64c946abc942710e712873252
