### ISSUE TITLE
@MockBean for ResourceLoader

### ISSUE THREAD

**Issue by pacey** [spring-cloud/spring-cloud-aws#257]
I want to write an integration test for some code that does some database manipulation and I'd like to mock the ResourceLoader, as I don't want the actual S3 lookups to happen. However, the MockBean annotation doesn't appear to be working for the ResourceLoader class.

Any ideas?

**Comment by rpiccoli** [comment]
Same for me...

**Comment by emmanuelproulx** [comment]
According to the documentation here: https://docs.spring.io/spring-framework/docs/3.0.0.M3/reference/html/ch04s11.html

"@Autowired may also be used for well-known "resolvable dependencies": the BeanFactory interface, the ApplicationContext interface, the ResourceLoader interface, the ApplicationEventPublisher interface and the MessageSource interface. These interfaces (and their extended interfaces such as ConfigurableApplicationContext or ResourcePatternResolver) will be automatically resolved, with no special setup necessary."

That said, if you put a breakpoint in your code, you will see that the ResourceLoader interface is implemented by the GenericApplicationContext, which is not something you should mock.

I might have to wrap my ResourceLoader inside a service just to be able to mock it. I wish there was a better solution.

**Comment by aemruli** [comment]
@pacey we add a since 2.0.RC2 a org.springframework.core.io.ProtocolResolver to the default resouceloader for resolving s3 resources. If you want to make that, then I suggest to add your own resolver.

So you can clear the ProtocolResolver and that you mock one if you want. Please see 
org.springframework.core.io.DefaultResourceLoader#getProtocolResolvers
