### ISSUE TITLE
AmazonEc2 instance is not found for DI

### ISSUE THREAD

**Issue by gschukin** [spring-cloud/spring-cloud-aws#28]
I have a simple Spring boot app and tring to inject default EC2Client but it seems that it is not created. When I try to inject S3Client evirything is fine.

```Java
@Configuration
@EnableAutoConfiguration(exclude = [
        AmazonRdsDatabaseRegistrar.class,
        MessagingAutoConfiguration.class,
        ElastiCacheAutoConfiguration.class,
        MailSenderAutoConfiguration.class])
@ComponentScan
public class Application implements CommandLineRunner {

    @Autowired
    private AmazonS3 amazonS3

    @Autowired
    private AmazonEC2 amazonEc2;

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args)
    }

    @Override
    void run(String... args) throws Exception {
        def list = amazonS3.listBuckets()
        log.info(list)
    }
}
```

**Comment by alainsahli** [comment]
Hi @gschukin 

Not all the AWS clients are created automatically. They are only created when needed and the AmazonEC2 client is not needed by now (instance metadata are accessed with EC2MetadataUtils). In your case you could create the AmazonEC2Client yourself like this:

```java
@Bean
public AmazonEC2 amazonEC2(AWSCredentialsProvider awsCredentialsProvider) {
    return new AmazonEC2Client(awsCredentialsProvider);
}
```

**Comment by gschukin** [comment]
Hi @alainsahli

Thank you for the answer. I thought that aws credentials and AmazonEC2Client on classpath was enough to have it provided as a bean. Also I was confused by documentation, as it states that client can be injected by default.

**Comment by aemruli** [comment]
Hello @gschukin 
in general we try to create as less resources (AWS clients) as possible. If you are only using an  `<context:context-instance-data />` then we are not creating an `AmazonEC2Client` because there is no need to create. If you enable the `user-tags-map` attribute inside the `context-instance-data` element, then we create the client (because we need it to fetch the tags in EC2). 
Therefore like @alainsahli described, you have to create the client on yourself if you are using the instance data support without user tags. 

I will re-open that issues and re-write the documentation to clarify that point, because it is currently confusing.
