### ISSUE TITLE
SpringBoot and RedisElastiCache Configuration

### ISSUE THREAD

**Issue by bhuvana27** [spring-cloud/spring-cloud-aws#291]
@aemruli 
Hi I am using Redis ElastiCache with Springboot.. While trying to connect to Elastic cache using @EnableElastiCache I am getting the below error.  Could you please let me know how to provide the configurations for redis elasticache in spring boot?

redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:199)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)

**Comment by aemruli** [comment]
Hello @bhuvana27 
I assume that you have a network problem with your connection. Please be aware that due to security reasons (Redis is missing a real authentication) you are not able to access Redis outside the AWS VPC (or within EC2 for classic deployments) - see https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/GettingStarted.AuthorizeAccess.html

You can have a look at https://github.com/spring-cloud/spring-cloud-aws/blob/5fde56ffaf1ff11a80ef99aa122142f2fc758387/spring-cloud-aws-integration-test/src/test/java/org/springframework/cloud/aws/cache/BootElastiCacheAwsTest.java which is  a memcached nad redis based test scenario. We only run those test inside the EC2 environment.

Closing this ticket as this is a question, feel free to re-open in case of any further questions.
