### ISSUE TITLE
Elastic Beanstalk Environment Params

### ISSUE THREAD

**Issue by ccit-spence** [spring-cloud/spring-cloud-aws#35]
Is it possible within the spring-cloud-aws project to pull the environment information from an Elastic Beanstalk setup?  

At the simplest level I would like to pull a custom tag from the Elastic Beanstalk configuration (not the instance) and use it dynamically to load a spring profile.

To further clarify the use case, our CI (Atlassian Bamboo) deploys the app into 3 environments.  Development, staging and production.  The goal would be for Spring to determine where it is loaded to take on profile properties from the environment.

**Comment by aemruli** [comment]
Hello @ccit-spence, 

thanks for your issue. Currently we do not have any dedicated Elastic Beanstalk support although we are very keen to add support. Initially we planned support that you can receive some metadata from the Elastic Beanstalk service, but never finished that. 

Elastic Beanstalk creates a stack while creating the environment. Therefore it might be useful for you that you use stack and receive some tags from the stack itself (e.g. `<aws-context:stack-configuration user-tags-map="stackTags"/>`). But I fear that you can not activate/passivate a profile in Spring because the application context is already loaded at that moment. But the tags might be useful for you while creating the beans (e.g. using expressions to access the tags). 

Like I said I am very keen to better understand your use case, maybe if you have some code running today you can share the basic ideas.

**Comment by ccit-spence** [comment]
@aemruli Right now I am evaluating some possibilities for deployment with EB.  Was curious how this project addressed EB.  You are right about the application context, could be something that needs to be done with -D params on launch.

The more manual way is change the properties based on stage.  Not an unreasonable solution since you could do a tag and push based on that change.  I try to automate everything as much as possible.

**Comment by maciejwalkowiak** [comment]
Active profile can be also set as the environment variable in Elastic Beanstalk environment. Considering our limited time we are not going to implement suggested change anytime soon. If anyone finds it really useful, please comment and ideally open a PR.
