### ISSUE TITLE
Add support for custom regions

### ISSUE THREAD

**Issue by gschukin** [spring-cloud/spring-cloud-aws#36]
AWS SDK allows to override region configuration with com/amazonaws/regions/override/regions.xml file, see RegionUtils.class.

But StaticRegionProvider relies on Regions emun, so it is impossible to pass custom region id with spring-boot-aws.

**Comment by aemruli** [comment]
Hello @gschukin, thanks for your issue. In the past we have used the Regions enum to have some kind of type safety. I will rework the `StaticRegionProvider` so that it receives a string. 

With that change we will unfortunately have a breaking change. Regions must be now specified by their logical name eu-west-1 instead of the enum name EU_WEST_1. But I think the breaking change is worth considering that the name eu-west-1 is the name that is documented in the AWS documentation. 

Would be great if you can test with RC2 (or a build snapshot if that works for you)!

**Comment by aemruli** [comment]
Fixed in 4eea859

**Comment by gschukin** [comment]
@aemruli I will try snapshot tomorrow. I think that it is possible to maintain backward compatibility by trying to cast value to emun #Regions.valueOf(...), if there is an exception then try to get region via RegionUtils. If both failed then something goes completely wrong.

**Comment by gschukin** [comment]
@aemruli Tested this change and everything works fine except running from within cloud. I've created a pull request #39 to fix invalid behavior if instance meta-data returned custom region
