### ISSUE TITLE
Don't automatically delete SQS messages upon receipt

### ISSUE THREAD

**Issue by twicksell** [spring-cloud/spring-cloud-aws#45]
When using @MessageMapping, the SimpleMessageListenerContainer seems to simply hand off the message to the handler and delete the message regardless of what happens during the actual invocation of the handler. This provides no method for error handling, and the message is completely lost. Message should not be auto-deleted unless the invocation is successful (and probably @SendTo as well).

This might bubble up to spring-messaging, but perhaps an optional Ackable argument to @MessageMapping methods would be useful. This would give users some direct control over deletion of messages from SQS.

**Comment by aemruli** [comment]
Hello @twicksell, with Issue #30 we have also added support for @MessageExceptionHandler methods to actually handle exceptions. You can decide based on the queue level if you have a redrive policy (and will receive the message according to your redrive policy) or to not use one a discard the message even in a event of an error. 

We delete the messages if there is no re-drive policy to avoid poison messages. I see two options first to add some support to the spring messaging api or to have a container wide configuration how often to a message has been delivered  (based on the ApproximateReceiveCount attribute). 

Would be great to have your feedback here!

**Comment by twicksell** [comment]
I understand the intent, but I think this is a behavior that needs to be configurable. If you consider a message not as a simple notification but as a mission-critical piece of information which must be processed successfully, the current approach leaves us with a problem. True, we can configure a redrive policy to have SQS force messages to another queue in the event of some application issue, but how would we then process messages from that queue without risking deleting them? 

There really should be an option to preserve messages regardless of of receive count or redrive configuration. Only if no exception is thrown, or if the exception is handled by an error hander (which does not throw some new exception), should a message be deleted. Exposing ApproximateReceiveCount as a message header might help developers in decided what to do in these situations however.

**Comment by alainsahli** [comment]
I added a new property (deleteMessageOnException) on the _SimpleMessageListenerContainer_ to define if a message must be deleted or not when an exception is thrown in the handler method. If this property is set to _false_, the messages are never deleted in case of an exception even if there is a redrive policy on the queue.

This property can be set on the _annotation-driven-queue-listener_ XML element or on the _SimpleMessageListenerContainerFactory_ when using Java config.

**Comment by ptolemy428** [comment]
We're evaluating options of using SimpleMessageListenerContainer in our Spring-based apps to integrate with AWS SQS. The current behavior of auto deletion of message after it has been processed by message handler is a show stopper for us. Given the mission-critical nature of our message processing, we need the container to support MANUAL deletion of the messages. 

Ideally the message deletion behavior should be configurable. We would like to have the message deletion under the control of the users. Our message processing can happen asynchronously, so just because that there are no exception being thrown, it does not mean the message has been completed processed and can be automatically deleted from the queue.

Please let me know if this requirement is considered as feasible and if so when is it likely to be added.

Cheers,

Larry
