### ISSUE TITLE
SimpleStorageResource fails to override getFile() from AbstractResource 

### ISSUE THREAD

**Issue by DiskImage** [spring-cloud/spring-cloud-aws#71]
I'm not sure if this was an intentional design choice or not, but SimpleStorageResource does not appear to override the base implementation of getFile() provided by AbstractResource. The implementation in AbstractResource just throws this exception:
```java
new FileNotFoundException(getDescription() + " cannot be resolved to absolute file path")
```

This seems extremely misleading. I spent an embarrassingly large amount of time trying to figure out why my s3 path, which worked just fine with the vanilla aws library's AmazonS3Client, suddenly was unable to resolve to an absolute file path. Could the SimpleStorageResource get an overriding implementation of getFile?

**Comment by aemruli** [comment]
Thanks @DiskImage I will have a look soon. Try to squeeze into 1.0.2

**Comment by Sintendo** [comment]
```URL getURL()``` has also not been implemented.

**Comment by aemruli** [comment]
@DiskImage we can not implement the getFile() method with a concrete implementation, because we are not operating on locale files while working with Amazon S3 resources. Therefore you should use GetInputStream() to read the file. Nevertheless I have added a more meaningful exception message to avoid any confusion. 

@Sintendo I have overwritten the getURL() method, which returns the method to the file. But you should also use getInputStream(). GetUrl() returns the correct url, but accessing the URL only makes sense for public object and not protected one. The latter will result in a 401.

**Comment by Sintendo** [comment]
The problem is I'm not the one calling ```getURL()```, or at least not directly anyway.

I was trying to set up an ```XsltViewResolver``` in such a way that it loads the XLS files from S3. Unfortunately, this currently fails when ```XsltView.getStylesheetSource()``` tries to do the following:

```return new StreamSource(resource.getInputStream(), resource.getURI().toASCIIString());```
