### ISSUE TITLE
Conflict between spring-cloud-aws-messaging and spring-boot-starter-amqp

### ISSUE THREAD

**Issue by thobson** [spring-cloud/spring-cloud-aws#77]
The cloud messaging module looks for @MessageMapping annotations and checks that they have a valid destination in QueueMessageHandler.getMappingForMethod:

```
if (messageMappingAnnotation.value().length < 1) {
  throw new IllegalStateException("@MessageMapping annotation must have at least one destination");
}
```

The problem is that spring boot amqp defines this annotation:

```
@Target({ElementType.METHOD, ElementType.ANNOTATION_TYPE})
@Retention(RetentionPolicy.RUNTIME)
@MessageMapping // No destination!
@Documented
public @interface RabbitListener { ... }
```
As a result it's not possible to listen for SQS and RabbitMQ messages in the same project

**Comment by thobson** [comment]
Now I think about it, the QueueMessageHandler should probably look for some prefix like sqs:queue-name because otherwise it will assume that all @MessageMapping annotations are destined for it

**Comment by alainsahli** [comment]
Hi @thobson, thanks for reporting this issue.

I fixed it by removing the check for a value. A prefix is not necessary because when the container listener starts it checks if the queue exists or not (see org.springframework.cloud.aws.messaging.listener.AbstractMessageListenerContainer#start()). If the queue does not exist, it is just ignored and a warning is logged.

The fix should be in tomorrow's SNAPSHOT version.
